vendor_id = 4057
product_id = 128
usage = 1
usage_page = 12
brightness = 60
keys_per_page = 15

[[keys]]
action = ""
icon = "calendar.svg"

[[keys]]
action = ""
icon = "clock.svg"

[[keys]]
action = "open https://github.com/EriksRemess/streamrs"
icon = "github.png"

[[keys]]
action = "open https://x.com/EriksRemess"
icon = "twitter.png"
